import {
  AlertEntity,
  CreateAlertInput,
  ListAlertsFilter,
  PaginatedAlertsResult,
  AlertStatus,
} from "./alert.entity";

export interface UpdateAlertStatusInput {
  status: AlertStatus;
  acknowledgedAt?: Date | null;
  acknowledgedBy?: string | null;
  resolvedAt?: Date | null;
  resolvedBy?: string | null;
  resolutionNotes?: string | null;
}

/**
 * Repository interface for durable alert persistence and lifecycle management.
 */
export interface IAlertRepository {
  /**
   * Persists a new alert decision.
   * Throws unique constraint conflict if (telemetryReadingId, ruleVersionId) already exists.
   */
  create(data: CreateAlertInput): Promise<AlertEntity>;

  /**
   * Finds an alert by unique identifier with well and rule version relations.
   */
  findById(id: string): Promise<AlertEntity | null>;

  /**
   * Checks for an existing alert generated by the specified reading and rule version (idempotency check).
   */
  findByReadingAndRuleVersion(
    telemetryReadingId: string,
    ruleVersionId: string,
  ): Promise<AlertEntity | null>;

  /**
   * Lists chronological alerts for a well with filtering and pagination.
   */
  listByWellId(
    wellId: string,
    filter?: ListAlertsFilter,
  ): Promise<PaginatedAlertsResult>;

  /**
   * Updates alert lifecycle state (acknowledge, resolve).
   */
  updateStatus(id: string, input: UpdateAlertStatusInput): Promise<AlertEntity>;
}
